import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from './components/header'; // Impor Header
import Footer from "./components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CollabSpace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}>
        <Header />
        
        {/* Container untuk layout dengan background hitam dan padding seragam */}
        <div className="container mx-auto px-4 max-w-7xl">
          {children}
        </div>

        <Footer />  
      </body>
    </html>
  );
}
